"""Valor total venda

Revision ID: 202c3065c2f4
Revises: 7c0d0ea2ba3f
Create Date: 2023-04-20 00:19:55.730064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202c3065c2f4'
down_revision = '7c0d0ea2ba3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('valor_total', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'valor_total')
    # ### end Alembic commands ###
