"""Correção relationship

Revision ID: 44f0b3476cb3
Revises: 202c3065c2f4
Create Date: 2023-04-20 13:53:51.049414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f0b3476cb3'
down_revision = '202c3065c2f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
