"""Campo imagem adicionado

Revision ID: 7f3e58b4a7af
Revises: 0d9d8484af23
Create Date: 2023-04-14 15:32:41.619194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3e58b4a7af'
down_revision = '0d9d8484af23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('imagem', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'imagem')
    # ### end Alembic commands ###
