"""Trocando nome da classe

Revision ID: affb654e8443
Revises: c648ec43172f
Create Date: 2023-04-06 16:04:18.765663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affb654e8443'
down_revision = 'c648ec43172f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('desenvolvedor', sa.String(length=50), nullable=True),
    sa.Column('plataforma', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('games_shop')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_shop',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('genero', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('desenvolvedor', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('plataforma', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('valor', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='games_pkey')
    )
    op.drop_table('game')
    # ### end Alembic commands ###
