"""Cria tabela games

Revision ID: c648ec43172f
Revises: 
Create Date: 2023-04-04 14:20:07.827200

"""
from alembic import op
import sqlalchemy as sadef


# revision identifiers, used by Alembic.
revision = 'c648ec43172f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('desenvolvedor', sa.String(length=50), nullable=True),
    sa.Column('plataforma', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
