"""Adicionando campo quantidade na tabela game

Revision ID: d1ef9c68d627
Revises: 7f3e58b4a7af
Create Date: 2023-04-16 16:51:21.628607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ef9c68d627'
down_revision = '7f3e58b4a7af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('quantidade', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'quantidade')
    # ### end Alembic commands ###
